#!/bin/bash
# AluminatAI GPU Agent Installer v0.2.0
set -euo pipefail

echo "🚀 AluminatAI GPU Agent Installer v0.2.0"
echo "========================================="
echo

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# ── Preflight checks ──────────────────────────────────────────────────────────

if ! command -v nvidia-smi &>/dev/null; then
    echo -e "${RED}❌ nvidia-smi not found. Install NVIDIA drivers first.${NC}"
    exit 1
fi
echo -e "${GREEN}✅ NVIDIA drivers detected${NC}"
echo "   GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"

if ! command -v python3 &>/dev/null; then
    echo -e "${RED}❌ Python 3 not found.${NC}"; exit 1
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
PYTHON_MINOR=$(python3 -c 'import sys; print(sys.version_info[1])')
PYTHON_MAJOR=$(python3 -c 'import sys; print(sys.version_info[0])')
if [ "$PYTHON_MAJOR" -lt 3 ] || [ "$PYTHON_MINOR" -lt 9 ]; then
    echo -e "${RED}❌ Python 3.9+ required (found $PYTHON_VERSION)${NC}"; exit 1
fi
echo -e "${GREEN}✅ Python $PYTHON_VERSION${NC}"

# ── Install directory ─────────────────────────────────────────────────────────

INSTALL_DIR="${INSTALL_DIR:-/opt/aluminatai-agent}"
echo
echo "📁 Install directory: $INSTALL_DIR"

if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}⚠️  Previous installation found${NC}"
    read -rp "   Remove and reinstall? (y/n) " REPLY
    echo
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        sudo systemctl stop aluminatai-agent 2>/dev/null || true
        sudo systemctl disable aluminatai-agent 2>/dev/null || true
        sudo rm -rf "$INSTALL_DIR"
    else
        echo "Installation cancelled."; exit 0
    fi
fi

# ── Copy source and install via pip ───────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check we are in the agent/ source directory (contains pyproject.toml one level up)
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
if [ ! -f "$REPO_ROOT/pyproject.toml" ]; then
    echo -e "${RED}❌ pyproject.toml not found in $REPO_ROOT${NC}"
    echo "Please run this script from the agent/ directory of the cloned repo."
    exit 1
fi

echo "📦 Installing agent package…"
sudo mkdir -p "$INSTALL_DIR"
sudo cp -r "$REPO_ROOT"/. "$INSTALL_DIR/"

# Install package + dependencies (editable install)
sudo python3 -m pip install -e "$INSTALL_DIR" --quiet
echo -e "${GREEN}✅ aluminatai-agent installed${NC}"

# ── User and directories ──────────────────────────────────────────────────────

if ! id -u aluminatai &>/dev/null; then
    sudo useradd --system --no-create-home --shell /usr/sbin/nologin aluminatai
fi
sudo mkdir -p /etc/aluminatai /var/log/aluminatai "$INSTALL_DIR/data"
sudo chown aluminatai:aluminatai /var/log/aluminatai "$INSTALL_DIR/data"

# ── API key setup ─────────────────────────────────────────────────────────────

echo
echo -e "${GREEN}🔑 API Key Setup${NC}"
echo "   Find your key at: https://aluminatiai.com/dashboard/setup"
echo
read -rp "   Enter API Key: " API_KEY

if [[ ! "$API_KEY" =~ ^alum_ ]]; then
    echo -e "${YELLOW}⚠️  Key should start with 'alum_'${NC}"
    read -rp "   Continue? (y/n) " REPLY
    echo
    [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "Cancelled."; exit 0; }
fi

# ── Environment file ──────────────────────────────────────────────────────────

echo "⚙️  Writing /etc/aluminatai/agent.env…"
sudo tee /etc/aluminatai/agent.env > /dev/null <<EOF
# AluminatAI Agent Configuration — generated by install.sh
ALUMINATAI_API_KEY=$API_KEY
ALUMINATAI_API_ENDPOINT=https://aluminatiai.com/api/metrics/ingest
SAMPLE_INTERVAL=5.0
UPLOAD_INTERVAL=60
METRICS_PORT=9100
LOG_LEVEL=INFO
EOF
sudo chmod 600 /etc/aluminatai/agent.env

# ── Systemd service ───────────────────────────────────────────────────────────

echo "🔧 Installing systemd service…"
sudo cp "$INSTALL_DIR/deploy/aluminatai-agent.service" /etc/systemd/system/aluminatai-agent.service
sudo systemctl daemon-reload
sudo systemctl enable aluminatai-agent
sudo systemctl start aluminatai-agent

sleep 3

if sudo systemctl is-active --quiet aluminatai-agent; then
    echo
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}✅ AluminatAI Agent is running!${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo
    echo "Commands:"
    echo "  Status:   sudo systemctl status aluminatai-agent"
    echo "  Logs:     sudo journalctl -u aluminatai-agent -f"
    echo "  Metrics:  curl localhost:9100/metrics"
    echo
    echo "Dashboard: https://aluminatiai.com/dashboard"
else
    echo -e "${RED}❌ Service failed to start${NC}"
    echo "Logs: sudo journalctl -u aluminatai-agent -n 50"
    exit 1
fi
